### ISSUE TITLE
shaking textbox if no input provided.

### ISSUE THREAD

**Issue by sanketshinde3001** [subh05sus/GeetaGPT#18]
Normally when empty input can leads to errors when we are using and LLM so its better to add this feature

**Comment by subh05sus** [comment]
sure, a great idea

**Comment by sanketshinde3001** [comment]
Can u please assign me this?

**Comment by subh05sus** [comment]
done, I forgot sorry

**Comment by sanketshinde3001** [comment]
Thank you
